export const ApiRoutes = {
  authBase: "/api/auth",
  authWildcard: "/api/auth/*splat",
  health: "/api/health",
  me: "/api/me",
  meImage: "/api/me/image",
  techniques: "/api/techniques",
  kyuProgram: "/api/kyu-program",
  events: "/api/events",
  event: "/api/events/:id",
  adminRanks: "/api/admin/ranks",
  adminStudents: "/api/admin/students",
  adminStudent: "/api/admin/students/:id",
  adminStudentImage: "/api/admin/students/:id/image",
  adminStudentRanks: "/api/admin/students/:id/ranks",
  adminStudentRank: "/api/admin/students/:id/ranks/:rankEntryId",
  adminStudentAttendance: "/api/admin/students/:id/attendance",
  adminStudentEvents: "/api/admin/students/:id/events",
  adminEvents: "/api/admin/events",
  adminEvent: "/api/admin/events/:id",
  adminEventImage: "/api/admin/events/:id/image",
  adminEventParticipants: "/api/admin/events/:id/participants",
} as const;
